const phoneCases = [
  {
    id: 1,
    name: "Phone Case 1",
    frontImage: "/products/PhoneCase1.JPG",
    hoverImage: "/products/PhoneCase1-1.JPG",
    price: 22.88,
  },
  {
    id: 2,
    name: "Phone Case 2",
    frontImage: "/products/PhoneCase2.JPG",
    hoverImage: "/products/PhoneCase2-1.JPG",
    price: 22.88,
  },
  {
    id: 3,
    name: "Phone Case 3",
    frontImage: "/products/PhoneCase3.JPG",
    hoverImage: "/products/PhoneCase3-1.JPG",
    price: 22.88,
  },
  {
    id: 4,
    name: "Phone Case 4",
    frontImage: "/products/PhoneCase4.JPG",
    hoverImage: "/products/PhoneCase4-1.JPG",
    price: 22.88,
  },
  {
    id: 5,
    name: "Phone Case 5",
    frontImage: "/products/PhoneCase5.JPG",
    hoverImage: "/products/PhoneCase5-1.JPG",
    price: 22.88,
  },
  {
    id: 6,
    name: "Phone Case 6",
    frontImage: "/products/PhoneCase6.JPG",
    hoverImage: "/products/PhoneCase6-1.JPG",
    price: 22.88,
  },
  {
    id: 7,
    name: "Phone Case 7",
    frontImage: "/products/PhoneCase7.JPG",
    hoverImage: "/products/PhoneCase7-1.JPG",
    price: 22.88,
  },
  {
    id: 8,
    name: "Phone Case 8",
    frontImage: "/products/PhoneCase8.JPG",
    hoverImage: "/products/PhoneCase8-1.JPG",
    price: 22.88,
  },
  {
    id: 9,
    name: "Phone Case 9",
    frontImage: "/products/PhoneCase9.JPG",
    hoverImage: "/products/PhoneCase9-1.JPG",
    price: 22.88,
  },
];
